name: orgamart
description: Organic product Ecommerce app


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^9.2.0
  badges: ^2.0.2
  flutter_custom_clippers: ^2.0.0
  new_gradient_app_bar: ^0.2.0
  animated_text_kit: ^4.2.1
  flutter_svg: ^1.0.3
  date_format: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/category/
    - assets/images/products/egg/
    - assets/images/products/meat/
    - assets/images/products/milk/
    - assets/images/products/oil/
    - assets/images/products/poultry/
    - assets/images/products/spices/
    - assets/images/products/vegetable/
    - assets/images/user/
    - assets/images/svg/





