import 'package:orgamart/model/item.dart';
import 'package:orgamart/model/category.dart';
import 'package:orgamart/model/offer.dart';

class Sample_DatabaseOfProducts {
  List<Category> allProducts = [
    Category(
        name: 'Vegetable',
        items: [
          Item(
              name: 'Brocolli',
              brand: 'Farmer',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 3,
              weight: 250,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/vegetable/brocolli.jpg'),
          Item(
            name: 'Pumpkin',
            brand: 'Farmer',
            type: 'Vegetable',
            discount: 0,
            initial_pricePerUnit: 2.5,
            weight: 1,
            packOrBottle: 'package',
            weightType: 'Kg',
            imagePath: 'assets/images/products/vegetable/pumpkin.jpg',
          ),
          Item(
              name: 'Potato',
              brand: 'Farmer',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 1.5,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/vegetable/potato.jpg'),
          Item(
              name: 'Tomato',
              brand: 'Farmer',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 2,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/vegetable/tomato.jpg'),
          Item(
              name: 'Onion',
              brand: 'Farmer',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 4,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/vegetable/onion.jpg'),
          Item(
              name: 'Cucumber',
              brand: 'Farmer',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 3,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/vegetable/cucumber.jpg'),
          Item(
              name: 'Cauliflower',
              brand: 'Farmer',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 2.7,
              weight: 1,
              packOrBottle: 'package',
              weightType: 'Kg',
              imagePath: 'assets/images/products/vegetable/cauliflower.jpg'),
        ],
        imagePath: 'assets/images/category/vegetable.jpg'),
    Category(
        name: 'Meat',
        imagePath: 'assets/images/category/meat.jpg',
        items: [
          Item(
              name: 'Beef',
              brand: 'Butcher',
              type: 'Vegetable',
              discount: 0,
              initial_pricePerUnit: 4,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/meat/beef.jpg'),
          Item(
              name: 'Mutton Chopped',
              brand: 'Butcher',
              type: 'Meat',
              discount: 0,
              initial_pricePerUnit: 5.5,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/meat/mutton chopped.jpg'),
          Item(
              name: 'Venison',
              brand: 'Butcher',
              type: 'Meat',
              discount: 0,
              initial_pricePerUnit: 7,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/meat/venison.jpg'),
          Item(
              name: 'Lamb Chopped',
              brand: 'Butcher',
              type: 'Meat',
              discount: 0,
              initial_pricePerUnit: 7,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/meat/lamb chop.jpg'),
        ]),
    Category(name: 'Egg', imagePath: 'assets/images/category/egg.jpg', items: [
      Item(
          name: 'Chicken',
          brand: 'Farmer',
          type: 'Egg',
          discount: 0,
          initial_pricePerUnit: 4.5,
          weight: 1,
          packOrBottle: 'Box',
          weightType: 'box(12)',
          imagePath: 'assets/images/products/egg/chicken egg.jpg'),
    ]),
    Category(
        name: 'Poultry',
        imagePath: 'assets/images/category/poultry.jpeg',
        items: [
          Item(
              name: 'Chicken',
              brand: 'Farmer',
              type: 'Poultry',
              discount: 0,
              initial_pricePerUnit: 3.5,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/poultry/chicken.jpeg'),
          Item(
              name: 'Duck Skinned',
              brand: 'Farmer',
              type: 'Poultry',
              discount: 0,
              initial_pricePerUnit: 4.5,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/poultry/duck skinned.jpg'),
          Item(
              name: 'Geese Skinned',
              brand: 'Farmer',
              type: 'Poultry',
              discount: 0,
              initial_pricePerUnit: 5.5,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/poultry/geese.jpg'),
          Item(
              name: 'Koel Skinned',
              brand: 'Farmer',
              type: 'Poultry',
              discount: 0,
              initial_pricePerUnit: 2,
              weight: 500,
              packOrBottle: 'package',
              weightType: 'gm',
              imagePath: 'assets/images/products/poultry/koel.jpg'),
        ]),
    Category(
      imagePath: 'assets/images/category/spices.jpg',
      name: 'Spices',
      items: [
        Item(
            name: 'Black pepper',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 10,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/black pepper.jpg'),
        Item(
            name: 'Chilli Powder',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 4.5,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/chiili powder.jpg'),
        Item(
            name: 'chilli',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 3.5,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/chilli.jpg'),
        Item(
            name: 'Garlic',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 2,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/garlic.jpg'),
        Item(
            name: 'Ginger',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 3,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/ginger.jpg'),
        Item(
            name: 'Salt',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 5,
            weight: 500,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/salt.jpg'),
        Item(
            name: 'Turmeric Powder',
            brand: 'Farmer',
            type: 'Spices',
            discount: 0,
            initial_pricePerUnit: 3,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/spices/turmeric powder.jpg'),
      ],
    ),
    Category(
      imagePath: 'assets/images/category/oil.jpg',
      name: 'Oil',
      items: [
        Item(
            name: 'Coconut Oil',
            brand: 'Farmer',
            type: 'Oil',
            discount: 0,
            initial_pricePerUnit: 12,
            weight: 500,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/oil/coconut oil.jpg'),
        Item(
            name: 'Olive Oil',
            brand: 'Farmer',
            type: 'Oil',
            discount: 0,
            initial_pricePerUnit: 14.5,
            weight: 500,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/oil/olive oil.jpg'),
        Item(
            name: 'Soybean Oil',
            brand: 'Farmer',
            type: 'Oil',
            discount: 0,
            initial_pricePerUnit: 3.5,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/oil/soybean oil.jpg'),
      ],
    ),
    Category(
      imagePath: 'assets/images/category/milk.jpg',
      name: 'Milk',
      items: [
        Item(
            name: 'Milk Liquid',
            brand: 'Farmer',
            type: 'Milk',
            discount: 0,
            initial_pricePerUnit: 5,
            weight: 500,
            packOrBottle: 'package',
            weightType: 'ml',
            imagePath: 'assets/images/products/milk/liquid milk.jpg'),
        Item(
            name: 'Milk Non-Fat',
            brand: 'Farmer',
            type: 'Milk',
            discount: 0,
            initial_pricePerUnit: 14.5,
            weight: 500,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/milk/liquid milk.jpg'),
        Item(
            name: 'Cheese',
            brand: 'Farmer',
            type: 'Milk',
            discount: 0,
            initial_pricePerUnit: 3.5,
            weight: 100,
            packOrBottle: 'package',
            weightType: 'gm',
            imagePath: 'assets/images/products/milk/cheese.jpg'),
      ],
    ),
  ];
  var alltrendingproducts = [
    Item(
        name: 'Brocolli',
        brand: 'Farmer',
        type: 'Vegetable',
        discount: 0,
        initial_pricePerUnit: 3,
        weight: 250,
        packOrBottle: 'package',
        weightType: 'gm',
        imagePath: 'assets/images/products/vegetable/brocolli.jpg'),
    Item(
        name: 'Milk Liquid',
        brand: 'Farmer',
        type: 'Milk',
        discount: 0,
        initial_pricePerUnit: 5,
        weight: 500,
        packOrBottle: 'package',
        weightType: 'ml',
        imagePath: 'assets/images/products/milk/liquid milk.jpg'),
    Item(
        name: 'Cheese',
        brand: 'Farmer',
        type: 'Cheese',
        discount: 0,
        initial_pricePerUnit: 14.5,
        weight: 500,
        packOrBottle: 'package',
        weightType: 'gm',
        imagePath: 'assets/images/products/milk/cheese.jpg'),
    Item(
        name: 'Beef',
        brand: 'Butcher',
        type: 'Vegetable',
        discount: 0,
        initial_pricePerUnit: 4,
        weight: 500,
        packOrBottle: 'package',
        weightType: 'gm',
        imagePath: 'assets/images/products/meat/beef.jpg'),
    Item(
        name: 'Chicken',
        brand: 'Farmer',
        type: 'Egg',
        discount: 0,
        initial_pricePerUnit: 4.5,
        weight: 1,
        packOrBottle: 'Box',
        weightType: 'box(12)',
        imagePath: 'assets/images/products/egg/chicken egg.jpg'),
    Item(
        name: 'Black pepper',
        brand: 'Farmer',
        type: 'Spices',
        discount: 0,
        initial_pricePerUnit: 10,
        weight: 100,
        packOrBottle: 'package',
        weightType: 'gm',
        imagePath: 'assets/images/products/spices/black pepper.jpg'),
    Item(
        name: 'Olive Oil',
        brand: 'Farmer',
        type: 'Oil',
        discount: 0,
        initial_pricePerUnit: 14.5,
        weight: 500,
        packOrBottle: 'package',
        weightType: 'gm',
        imagePath: 'assets/images/products/oil/olive oil.jpg'),
    Item(
        name: 'Soybean Oil',
        brand: 'Farmer',
        type: 'Oil',
        discount: 0,
        initial_pricePerUnit: 3.5,
        weight: 100,
        packOrBottle: 'package',
        weightType: 'gm',
        imagePath: 'assets/images/products/oil/soybean oil.jpg'),
  ];
  var discountedProducts = [
    Item(
      name: 'Coconut Oil',
      brand: 'Farmer',
      type: 'Oil',
      discount: 20,
      initial_pricePerUnit: 12,
      weight: 500,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/oil/coconut oil.jpg',
    ),
    Item(
      name: 'Pumpkin',
      brand: 'Farmer',
      type: 'Vegetable',
      discount: 30,
      initial_pricePerUnit: 2.5,
      weight: 1,
      packOrBottle: 'package',
      weightType: 'Kg',
      imagePath: 'assets/images/products/vegetable/pumpkin.jpg',
    ),
    Item(
      name: 'Onion',
      brand: 'Farmer',
      type: 'Vegetable',
      discount: 20,
      initial_pricePerUnit: 4,
      weight: 500,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/vegetable/onion.jpg',
    ),
    Item(
      name: 'Ginger',
      brand: 'Farmer',
      type: 'Spices',
      discount: 20,
      initial_pricePerUnit: 3,
      weight: 100,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/spices/ginger.jpg',
    ),
    Item(
      name: 'Salt',
      brand: 'Farmer',
      type: 'Spices',
      discount: 20,
      initial_pricePerUnit: 5,
      weight: 500,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/spices/salt.jpg',
    ),
    Item(
      name: 'Turmeric Powder',
      brand: 'Farmer',
      type: 'Spices',
      discount: 10,
      initial_pricePerUnit: 3,
      weight: 100,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/spices/turmeric powder.jpg',
    ),
    Item(
      name: 'Pumpkin',
      brand: 'Farmer',
      type: 'Vegetable',
      discount: 30,
      initial_pricePerUnit: 2.5,
      weight: 1,
      packOrBottle: 'package',
      weightType: 'Kg',
      imagePath: 'assets/images/products/vegetable/pumpkin.jpg',
    ),
    Item(
      name: 'Onion',
      brand: 'Farmer',
      type: 'Vegetable',
      discount: 20,
      initial_pricePerUnit: 4,
      weight: 500,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/vegetable/onion.jpg',
    ),
    Item(
      name: 'Ginger',
      brand: 'Farmer',
      type: 'Spices',
      discount: 50,
      initial_pricePerUnit: 3,
      weight: 100,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/spices/ginger.jpg',
    ),
    Item(
      name: 'Salt',
      brand: 'Farmer',
      type: 'Spices',
      discount: 30,
      initial_pricePerUnit: 5,
      weight: 500,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/spices/salt.jpg',
    ),
    Item(
      name: 'Turmeric Powder',
      brand: 'Farmer',
      type: 'Spices',
      discount: 30,
      initial_pricePerUnit: 3,
      weight: 100,
      packOrBottle: 'package',
      weightType: 'gm',
      imagePath: 'assets/images/products/spices/turmeric powder.jpg',
    ),
  ];
  List<Offer> offerList = [
    Offer(
        title: 'Amazing!!',
        imagepath: 'assets/images/products/oil/coconut oil.jpg',
        offerDetail: 'Get 20% dsicount on coconut oil'),
    Offer(
        title: 'Flat 30!',
        imagepath: 'assets/images/products/vegetable/pumpkin.jpg',
        offerDetail: ' Flat 30% discount on any pumpkin!'),
    Offer(
        title: 'Half price!!',
        imagepath: 'assets/images/products/spices/ginger.jpg',
        offerDetail: 'Get 50% discount on ginger'),
    Offer(
        title: 'Limited 20%',
        imagepath: 'assets/images/products/spices/salt.jpg',
        offerDetail: '20% discount on onions!!')
  ];
}
